schema: workflow/2022.04
name: Get Toy Photos
settings:
  error_notification: true
triggers:
- id: hi_a1HkNY8
steps:
- namespace: get_photos
  runtime: nodejs18.x
  uses: "./get_photos/entry.js"
  props:
    google_photos:
      authProvisionId: apn_z8h1AD
    album: AMfAEpztLpk-HzVAka8zgRTM32Q2dL4LvDAJhp-lgloXaT27jEWFnFvpDbgOOfFYxoVmFwKr4E34
    cache:
      storeId: ds_n5uXlr
- namespace: return_http_response
  runtime: nodejs18.x
  uses: http-return-http-response@0.0.3
  props:
    resStatusCode: 200
    resBody: '{ "photos": steps.get_photos.$return_value }'

