schema: workflow/2022.04
name: Get Toy Photos
settings:
  error_notification: true
triggers:
- id: hi_a1HkNY8
steps:
- namespace: google_photos
  runtime: nodejs18.x
  uses: "./google_photos/entry.js"
  props:
    google_photos:
      authProvisionId: apn_z8h1AD

