schema: workflow/2022.04
name: Office to PDF Workflow with Foxit
inactive: true
settings:
  error_notification: true
triggers:
- id: sub_7gUrexE
  uses: sc_v4ieJMb
  props:
    dropbox:
      authProvisionId: apn_LMho37
    includeLink: false
    includeMediaInfo: false
    path:
      __lv:
        label: "/Foxit"
        value: "/foxit"
    recursive: true
steps:
- namespace: End_if_output
  runtime: nodejs20.x
  uses: "./End_if_output/entry.js"
  props:
    _filter:
      continue: 'false'
      rules:
        t: and
        r:
        - a: "{{steps.trigger.event.path_display}}"
          op: str/
          b: "/output/"
- namespace: download_to_tmp
  runtime: python3.12
  uses: "./download_to_tmp/entry.py"
- namespace: upload_to_foxit
  runtime: python3.12
  uses: "./upload_to_foxit/entry.py"
- namespace: create_conversion_job
  runtime: python3.12
  uses: "./create_conversion_job/entry.py"
- namespace: check_job
  runtime: python3.12
  uses: "./check_job/entry.py"
- namespace: download_result_to_tmp
  runtime: python3.12
  uses: "./download_result_to_tmp/entry.py"
- namespace: upload_result
  runtime: nodejs20.x
  uses: dropbox-upload-file@1.0.0
  props:
    dropbox:
      authProvisionId: apn_LMho37
    path:
      __lv:
        label: "/Foxit"
        value: "/foxit"
    name: output/{{steps.download_result_to_tmp.$return_value.filename}}
    filePath: "{{steps.download_result_to_tmp.$return_value.path}}"

